---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-1
  namespace: democratic-csi
  labels:
    app: grafana
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
