# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sz72Q+oiOu0eUNXN7aMyXVIR1pM=,iv:j4UDMlvx2472KcI4gh7sBtAJRen7ZD1pSbouSxRPUBw=,tag:Bc6elaY9h4Hhvk3JMUDeHg==,type:str]
    api-key: ENC[AES256_GCM,data:QcLbDPe2ZDsc4IJcIrKglHkdjC71ZeJ0SWAOsokCunwbPO/MHg==,iv:Lul7oulIapADqBS8cIIWsCCwZ+U/Wur4AnXdZ2JzPRs=,tag:Bu+xsuv4psQ85eJHTAREaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk2sthw65qffw05t2kuf6he5pkaxaw3mk5xwmmyvd6pm2turjeasnqwqkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUQ0eHBKMVBkcmdMTS9z
            REkyWlhOenRwMzU1TFVFVllSaTFLc0hRNldBCk0zRVFvVFBLRk9QZHdnNUJaOHo3
            Z3F4bU04ZkRncE1WYlBWczRJL0hZN2sKLS0tIDV6aStuQktxemVtOEJLOXdnc0VR
            amN1OW5zMmR5TWEvYUdFVnBDL0ljeHcKfHasYiIV6hzcZA3UWXzkCakHuTc3c8Ws
            ilWQ3nYRysyhlYMcIbxc543E0R2GeD9J7gYdDBRn3FngZDiOJAWRvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T20:09:37Z"
    mac: ENC[AES256_GCM,data:wD4RGmXXf/+iYsd7qxdVK0TpCkJp7vY/3/NyZdtTS4pxT41N3A/QtemKShH6fo3r4MjmZn2HfR3fSORvkAaEHIAjmVrTWrw1gvKQ2bmHjy0YG0Pe4fYcqrRQ4Gxhea85zU+tC6fj43RPCMbHv8iZPBTOELbN+6Ifdms9JS5/vG8=,iv:POZkzNbQ2CqujJm9sJzZ4i/FrO+xUGrOSKRGq7PPBEE=,tag:78LzWIn3BKGf25Ui1wf+5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
