# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:33vjLFK8TtPkfU+bakihpbb7Y6s=,iv:Rkrpu0+TcQ6Uw3X+N12H2n9OUVVT6YXIaTZv7m0W0io=,tag:PYxVBphS7ow+kHBJQNhgLQ==,type:str]
    api-key: ENC[AES256_GCM,data:QHGmEkrbRVDZ9zu8yiiuyZy1rnN4+oIgpaaZfFukK0Fuc1Dxww==,iv:zFWpGpD1fT8qpgO9Bf7xd35jKa2ooJYEb4xsmT7e+C4=,tag:yZCB7Rwm9UIS+VbyAMzvqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk2sthw65qffw05t2kuf6he5pkaxaw3mk5xwmmyvd6pm2turjeasnqwqkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT1ZOait4Nk9BY21tenRW
            MDJ1U3Nvak5ZWjl3eTQ2eWFNMWpnaG0rWldRCnlDalYxd3FJbGlDY0xWZElKSDV6
            VXY1RFllQ2JMdHd6TTAzdURudmp0WkUKLS0tIDNzU1BHZmhvcUN6QUpJanM2K2hD
            MUxwZkdsNno4N2psc256WEx2Ky9JaDgKSRPewPpGlt6SCs7VCE7Iji1Yqim5gler
            CAFSNdZHfzRjpb4Ba9NiCGin797ySWmMjtRkweFJ/xTq4d6iL/ZmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-28T23:37:19Z"
    mac: ENC[AES256_GCM,data:lBVbCTFIwzQ02DNHjnYW6PWgdyl+v2FYm3Wi4QBvG5QVyK7JTajE21MWSx7UIsw+5Y8K2O1ZJIOzGWfI2Zp9iRtX9byO/k8oDViUvBesp/ta0lMj3rsTFQhUzbdkm3pV66EroGMv9fBoN8LSG4Wsoi6rzcThpayvHL//8GuV9mY=,iv:lY5tTFOII3T8g8o8vPVv0bOZJqd6jNTXI9TGCeQTkng=,tag:HCrrarue8tc7ZaEfOUTH0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
