---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "rancher-domain"
  namespace: cattle-system
spec:
  secretName: "tls-rancher-ingress"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "rancher.${SECRET_DOMAIN}"
  dnsNames:
    - "rancher.${SECRET_DOMAIN}"
