kind: Secret
ansible_user: ENC[AES256_GCM,data:edYOy6ls,iv:7XkZ1slB/GXQWnnORy8Biq82kePBSee4tuQtstsHTEY=,tag:PqskLirLiszxiqCN+KkiLQ==,type:str]
ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk2sthw65qffw05t2kuf6he5pkaxaw3mk5xwmmyvd6pm2turjeasnqwqkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ajlHczBGT0hNVkhRbHZE
            S213Z2VBdStYVER0a3N4K1l0MjdnbEhNbXlVClNtY3prTkJQZ2M3RStyRFkxUGw2
            QzMzZU5oRlZQVkhkd2loNElNc2FOWHMKLS0tIFI4RzFpeHlFVm4rUXFNczlVOU9r
            djV6YnFISFoxWE9vdE1IRGZLUjZ4cGcKEJlvgN+VR58bydUOrRLLH31hPDzolv4L
            /peJJwVjT4Ycp2jr6NBHJ0EuLyd1yXil585ueezmLM+wdxOUMBLUcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-28T23:37:19Z"
    mac: ENC[AES256_GCM,data:zj0hv/DvPy2hEWDQfwufPOnbT0eGQcKspCswYUea9pVdOUiEBwPYOutDsOxqa0lDIJf4UDsYFjeckHJjpF0/v26WCZvmFSTPh0Iw8TSzQY0/hWXRNuqxm0y9OGaqRgh4XQvHCBjTLDnqVHmctQcC3o5/lwn2CWf9aS8wKHg6MQw=,iv:8EzYT4V+p2LOVrExfGaKRoBX2HM/4rNxLIJ2ncitrVQ=,tag:m3B20e8hfJke4zedWgeC7w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
