---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage-minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 11.7.19
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    envFrom:
      - secretRef:
          name: minio-creds
    env:
      - name: TZ
        value: "${TZ}"
      - name: MINIO_PROMETHEUS_URL
        value: http://kube-prometheus-stack-prometheus.monitoring:9090
      - name: MINIO_PROMETHEUS_JOB_ID
        value: minio
      - name: MINIO_UPDATE
        value: "off"
      - name: MINIO_BROWSER_REDIRECT_URL
        value: "https://minio.${SECRET_DOMAIN}"
      - name: MINIO_SERVER_URL
        value: "https://s3.${SECRET_DOMAIN}"
    auth:
      existingSecret: minio-creds
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-forward-auth@kubernetescrd"
        hajimari.io/enable: "true"
        hajimari.io/icon: "file-table-box"
        hajimari.io/group: "storage"
        hajimari.io/appName: "minio"
      hostname: &consoleHost "minio.${SECRET_DOMAIN}"
      tls: true
      extraTls:
        - hosts:
            - *consoleHost
    apiIngress:
      enabled: true
      hostname: &apiHost "s3.${SECRET_DOMAIN}"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-forward-auth@kubernetescrd"
        hajimari.io/enable: "true"
        hajimari.io/icon: "file-table-box"
        hajimari.io/group: "storage"
        hajimari.io/appName: "minio-api"
      tls: true
      extraTls:
        - hosts:
            - *apiHost
    podSecurityContext:
      enabled: true
      fsGroup: 100
    containerSecurityContext:
      enabled: true
      runAsUser: 568
      runAsNonRoot: true
    persistence:
      enabled: true
      existingClaim: minio-nfs
    prometheus:
      servicemonitor:
        enabled: true
