---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage-minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-truenas-nfs
  resources:
    requests:
      storage: 1001Gi
