# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:XwPdIFNVqYdyt38VWCRlLBWYGliveXe4KgnoPAsDc+W1xJ8BMg==,iv:A+PEJlTHDQEd/K17uXRY9UFYF6Vue22y1U15hUiOAZg=,tag:CxuxWCp80/eLYkKW/UxI7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk2sthw65qffw05t2kuf6he5pkaxaw3mk5xwmmyvd6pm2turjeasnqwqkx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNWVzWnVWZitSL084a1lt
            dUE4ZUE5UEdoU0VPeFVXNVBpNkpCUk52NkY0CnJSaDFZWjdaRTVuektRUGEvR1M4
            K0ZNQ01VVFI1RytiQk8rZklFc0VndHcKLS0tIHdiRmU0WWIwN3ZvQncxNEprd2ZE
            TFZpTy8xV1VVOVpwQlVMK2oxc1cxSDgKMR0QjbmPUp4w9jxoh/0tsofX5w4Noiu9
            oLR2bBgUYx543gNqjuzf9gooQR7qve4cwHApScf1YYZNs+2+IYRMmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-28T23:37:18Z"
    mac: ENC[AES256_GCM,data:Uc2UPkCw2Q693Nkn07MhQ/6RdXYyVHeFLLilEGBjDNN6ODFpOTiaien1lXg29Tsu88faA/yj2eL2rTJ+3VxbheWIK0hrVk+V0jz/Ibs24cf/koWjfe5u78JACBJFjZwncSttw+Ea6wDQusbgutreqzJI/rbg5L3TmzcKmgStuPY=,iv:g5LiehlZLDsoWLlnvlmeEcUEJ9prMzgNl8Z5E20CZjM=,tag:aDiPZ7LDsCHyQzil9Fm6uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
