---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.truenas-nfs"
      installCRD: false

    driver:
      # see the driver-config-secret.yaml template for syntax
      # existingConfigSecret: secret-democratic-csi-driver-config-nfs
      config:
        ## NOTE: if setting an existing secret you must still set `driver.config.driver`
        ## to the appropriate (equivalent) 'driver' value used in the secret,
        ## as the value is used by the chart for other purposes beyond secret creation
        driver: freenas-api-nfs
        instance_id: B8712266-C1B5-4DCD-9DFD-C6646C0AD3A4
        httpConnection:
          protocol: http
          port: 80
          apiKey: "${SECRET_TRUENAS_APIKEY}"
          allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: 192.168.0.22
          port: 22
          username: root
          privateKey: "${SECRET_TRUENAS_PRIVATEKEY}"
        zfs:
          cli:
            sudoEnabled: true
            datasetProperties:
              "org.freenas:description": "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
            datasetParentName: data/k8s/nfs/v
            detachedSnapshotsDatasetParentName: data/k8s/nfs/s
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
        nfs:
          shareCommentTemplate: "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: 192.168.0.22
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: "wheel"
          shareMapallUser: ""
          shareMapallGroup: ""

    controller:
      enabled: true
      hostNetwork: true # set false if fails
      hostIPC: true # set false if fails
      podAnnotations:
        secret.reloader.stakater.com/reload: "secret-democratic-csi-driver-config-nfs"
      strategy: deployment
      externalAttacher:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalProvisioner:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalResizer:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 37M
          limits:
            cpu: 11m
            memory: 37M
      external Snapshotter:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalHealthMonitorController:
        enabled: false
      livenessProbe:
        enabled: true
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: debug
        # ### for the controller, manually mount from the remote NFS server on start,
        # ### so it can dynamically create PVC (the "crude" part)
        # ### ref: https://gist.github.com/admun/4372899f20421a947b7544e5fc9f9117
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "mkdir -p /mnt/nfs; mount ${SECRET_TRUENAS_IP}:/mnt/ssdpool/csi/nfs/v /mnt/nfs"]
        #   preStop:
        #     exec:
        #       command: ["/bin/sh","-c","umount /mnt/nfs"]
        resources:
          requests:
            cpu: 35m
            memory: 127M
          limits:
            cpu: 35m
            memory: 127M
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true

      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          # effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists

    node:
      enabled: true
      rbac:
        enabled: true
      hostNetwork: true
      hostIPC: true
      kubeletHostPath: /var/lib/kubelet
      podAnnotations:
        secret.reloader.stakater.com/reload: "secret-democratic-csi-driver-config-nfs"
      livenessProbe:
        enabled: true
      mount:
        # should fsck be executed before mounting the fs
        checkFilesystem:
          xfs:
            enabled: true
          ext4:
            enabled: true

      cleanup:
        resources:
          requests:
            cpu: 11m
            memory: 14M
          limits:
            cpu: 11m
            memory: 14M
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: debug
        resources:
          requests:
            cpu: 35m
            memory: 127M
          limits:
            cpu: 35m
            memory: 127M
      driverRegistrar:
        resources:
          requests:
            cpu: 11m
            memory: 14M
          limits:
            cpu: 11m
            memory: 14M

      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          # effect: NoSchedule

    storageClasses:
      - name: csi-truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete # Delete, Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
          - sec=sys

    # volumeSnapshotClasses:
    #   - name: csi-truenas-nfs
    #     deletionPolicy: Delete # Delete, Retain

    csiProxy:
      resources:
        requests:
          cpu: 11m
          memory: 14M
        limits:
          cpu: 11m
          memory: 14M
