---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - democratic-csa.yaml
  - kubernetes-dashboard.yaml
  - longhorn-system.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - system-upgrade.yaml
  - cattle-system.yaml
  - minio.yaml
